#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.f22pkj31.bean
  mapperLocations: classpath:mapper/*.xml
server:
  servlet:
    context-path: /leadcampus
web:
#  upload-path: C:/eclipse/eclipse-jee-oxygen-2-win32-x86_64/boot/leadcompusfile/
  upload-path: /home/tomcat/apache-tomcat-8.5.8/webapps/leadcompusfile/
---

#开发配置

spring:
  profiles: dev
  mvc.static-path-pattern: /**
  resources.static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  datasource:
    url: jdbc:mysql://47.95.14.18:3306/leadcampus?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: uAiqwVwjJ8-i
    driver-class-name: com.mysql.jdbc.Driver

